#!/bin/bash
#SBATCH --job-name=rebuild_rag_embeddings      # Job name for the GRPO training
#SBATCH --partition=gpu,gpu-preempt      # CPUs are in much greater supply, thus we can use a lot of them
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --ntasks=8                # 8 CPUs are good for data loading and evaluation threads
#SBATCH --gpus=1
#SBATCH --mem=60G                        # Hopefully enough RAM
#SBATCH --output=logs/embeddings_%j.out # Log output to a 'logs' directory
#SBATCH --error=logs/embeddings_%j.err  # Log errors to a 'logs' directory
#SBATCH --constraint="a100"
# Job information
echo "==============================================="
echo "CICS Chatbot"
echo "==============================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Job Name: $SLURM_JOB_NAME"
echo "Node: $SLURMD_NODENAME"
echo "Start Time: $(date)"
echo "Working Directory: $(pwd)"
echo "==============================================="

source .venv/bin/activate
apptainer exec --nv ollama.sif ollama serve > ollama.log 2>&1 &
python pipelines/rebuild_database.py